### ISSUE TITLE
Zero crossing detection

### ISSUE THREAD

**Issue by tgingold** [dae-cpp/dae-cpp#33]
Hello,
I understand I can stop the solver with `stop_condition`, but is there a possibility to stop on zero crossing ?

**Comment by ikorotkin** [comment]
Hi @tgingold,

Zero crossing detection is not implemented explicitly. A possible workaround would be overriding `stop_condition` function from the `RHS` class (https://github.com/ikorotkin/dae-cpp/blob/master/src/RHS.h).
This function is called by the solver every time step and provides the current solution vector `x` and the time `t` that can be used to stop on the user-defined event:

```cpp
    /*
     * User-defined condition, when the solver should stop and return the
     * solution at the current time step
     */
    virtual bool stop_condition(const state_type &x, const double t)
    {
        return false;
    }
```

It returns `false` by default but you can implement your custom condition (when you want the solver to stop) and return `true`.

The adaptive time-stepping algorithm of the solver should refine the time step if any of the variables are rapidly changing. If the solver struggles to converge, it might be worth trying another adaptive time-stepping method or changing its parameters.
Reducing the maximum allowed time step `dt_max` and the initial time step `dt_init` may help too. Another way to improve stability is to use BDF-1 time integrator.

The full list of the solver parameters with comments is in `SolverOptions` class: https://github.com/ikorotkin/dae-cpp/blob/master/src/solver_options.h

**Comment by ikorotkin** [comment]
This is related to the old (now unsupported) version of `dae-cpp`. I am closing this issue for now.
